# Display
#WIDTH  = 1920
#HEIGHT = 1080
WIDTH  = 1366
HEIGHT = 720
ASPECT_RELATION_PLAYER = 2.4
ASPECT_RELATION_CHAT = 0.6
WIDTH_PLAYER_SPRITE = 100
HEIGHT_CHAT = 680
PLAYER_SURFACE = (WIDTH_PLAYER_SPRITE, int(WIDTH_PLAYER_SPRITE * ASPECT_RELATION_PLAYER))
CHAT_SURFACE = (int(HEIGHT_CHAT * ASPECT_RELATION_CHAT), HEIGHT_CHAT)

# Level config
LEVEL_TIME = 120
FALL_SPEED = 0.9
PLAYER_SPEED = 0.5
LEFT_LIMIT = 30
RIGHT_LIMIT = WIDTH - LEFT_LIMIT
GROUND_LEVEL = HEIGHT - 70
BOTTOM_LIMIT = HEIGHT + 100
INITIAL_HEALT = 30
FRAME_PER_SPRITE = 5

# Level 1
RATIO_NEW_OBJECT_LV_1 = 0.5
RATIO_OBJECT_1_LV_1 = RATIO_NEW_OBJECT_LV_1 + RATIO_NEW_OBJECT_LV_1 * 0.3
RATIO_OBJECT_2_LV_1 = RATIO_OBJECT_1_LV_1 + RATIO_NEW_OBJECT_LV_1 * 0.3
RATIO_BAD_OBJECT_LV_1 = RATIO_OBJECT_2_LV_1 + RATIO_NEW_OBJECT_LV_1 * 0.4

# Level 2
RATIO_NEW_OBJECT_LV_2 = 0.5
RATIO_OBJECT_1_LV_2 = RATIO_NEW_OBJECT_LV_2 + RATIO_NEW_OBJECT_LV_2 * 0.3
RATIO_OBJECT_2_LV_2 = RATIO_OBJECT_1_LV_2 + RATIO_NEW_OBJECT_LV_2 * 0.3
RATIO_BAD_OBJECT_LV_2 = RATIO_OBJECT_2_LV_2 + RATIO_NEW_OBJECT_LV_2 * 0.4

# Level 3
RATIO_NEW_OBJECT_LV_3 = 0.5
RATIO_OBJECT_1_LV_3 = RATIO_NEW_OBJECT_LV_3 + RATIO_NEW_OBJECT_LV_3 * 0.3
RATIO_OBJECT_2_LV_3 = RATIO_OBJECT_1_LV_3 + RATIO_NEW_OBJECT_LV_3 * 0.3
RATIO_BAD_OBJECT_LV_3 = RATIO_OBJECT_2_LV_3 + RATIO_NEW_OBJECT_LV_3 * 0.4

# Level 4
RATIO_NEW_OBJECT_LV_4 = 0.5
RATIO_OBJECT_1_LV_4 = RATIO_NEW_OBJECT_LV_4 + RATIO_NEW_OBJECT_LV_4 * 0.3
RATIO_OBJECT_2_LV_4 = RATIO_OBJECT_1_LV_4 + RATIO_NEW_OBJECT_LV_4 * 0.3
RATIO_BAD_OBJECT_LV_4 = RATIO_OBJECT_2_LV_4 + RATIO_NEW_OBJECT_LV_4 * 0.4

# Level 5
RATIO_NEW_OBJECT_LV_5 = 0.5
RATIO_OBJECT_1_LV_5 = RATIO_NEW_OBJECT_LV_5 + RATIO_NEW_OBJECT_LV_5 * 0.3
RATIO_OBJECT_2_LV_5 = RATIO_OBJECT_1_LV_5 + RATIO_NEW_OBJECT_LV_5 * 0.3
RATIO_BAD_OBJECT_LV_5 = RATIO_OBJECT_2_LV_5 + RATIO_NEW_OBJECT_LV_5 * 0.4

# Locations menus
PLAY_BUTTON = (200, 200)
CREDITS_BUTTON = (200, 200)
STORY_INIT_BUTTON = (200, 200)
SURVIVAL_INIT_BUTTON = (200, 200)


# HUB
TIMER_LOCATION = (int(WIDTH / 2), 30)
OBJECT_1_ICON_LOCATION = (int(WIDTH / 2) - 95, 30)
OBJECT_1_COUNTER_LOCATION = (int(WIDTH / 2) - 70, 30)
OBJECT_2_ICON_LOCATION = (int(WIDTH / 2) + 90, 30)
OBJECT_2_COUNTER_LOCATION = (int(WIDTH / 2) + 70, 30)
HEALT_BAR_PORTION_SIZE = (int(WIDTH / (2 * INITIAL_HEALT)), 15)
HEALT_LOCATION = (int(WIDTH / 2), HEIGHT - 20)
