# Display
#WIDTH  = 1920
#HEIGHT = 1080
WIDTH  = 1366
HEIGHT = 720

# Level config
LEVEL_TIME = 120
FALL_SPEED = 10
PLAYER_SPEED = 0.5
LEFT_LIMIT = 30
RIGHT_LIMIT = WIDTH - LEFT_LIMIT
GROUND_LEVEL = HEIGHT - 70
BOTTOM_LIMIT = HEIGHT + 100
INITIAL_HEALT = 30

# Level 1
RATIO_NEW_OBJECT_LV_1 = x
RATIO_OBJECT_1_LV_1 = RATIO_NEW_OBJECT_LV_1 + RATIO_NEW_OBJECT_LV_1 * y
RATIO_OBJECT_2_LV_1 = RATIO_OBJECT_1_LV_1 + RATIO_NEW_OBJECT_LV_1 * z
RATIO_BAD_OBJECT_LV_1 = RATIO_OBJECT_2_LV_1 + RATIO_NEW_OBJECT_LV_1 * w

# Level 2
RATIO_NEW_OBJECT_LV_2 = x
RATIO_OBJECT_1_LV_2 = RATIO_NEW_OBJECT_LV_2 + RATIO_NEW_OBJECT_LV_2 * y
RATIO_OBJECT_2_LV_2 = RATIO_OBJECT_1_LV_2 + RATIO_NEW_OBJECT_LV_2 * z
RATIO_BAD_OBJECT_LV_2 = RATIO_OBJECT_2_LV_2 + RATIO_NEW_OBJECT_LV_2 * w

# Level 3
RATIO_NEW_OBJECT_LV_3 = x
RATIO_OBJECT_1_LV_3 = RATIO_NEW_OBJECT_LV_3 + RATIO_NEW_OBJECT_LV_3 * y
RATIO_OBJECT_2_LV_3 = RATIO_OBJECT_1_LV_3 + RATIO_NEW_OBJECT_LV_3 * z
RATIO_BAD_OBJECT_LV_3 = RATIO_OBJECT_2_LV_3 + RATIO_NEW_OBJECT_LV_3 * w

# Level 4
RATIO_NEW_OBJECT_LV_4 = x
RATIO_OBJECT_1_LV_4 = RATIO_NEW_OBJECT_LV_4 + RATIO_NEW_OBJECT_LV_4 * y
RATIO_OBJECT_2_LV_4 = RATIO_OBJECT_1_LV_4 + RATIO_NEW_OBJECT_LV_4 * z
RATIO_BAD_OBJECT_LV_4 = RATIO_OBJECT_2_LV_4 + RATIO_NEW_OBJECT_LV_4 * w

# Level 5
RATIO_NEW_OBJECT_LV_5 = x
RATIO_OBJECT_1_LV_5 = RATIO_NEW_OBJECT_LV_5 + RATIO_NEW_OBJECT_LV_5 * y
RATIO_OBJECT_2_LV_5 = RATIO_OBJECT_1_LV_5 + RATIO_NEW_OBJECT_LV_5 * z
RATIO_BAD_OBJECT_LV_5 = RATIO_OBJECT_2_LV_5 + RATIO_NEW_OBJECT_LV_5 * w

# Locations menus
PLAY_BUTTON = (x, y)
CREDITS_BUTTON = (x, y)
STORY_INIT_BUTTON = (x, y)
SURVIVAL_INIT_BUTTON = (x, y)


# HUB
TIMER_LOCATION = (int(WIDTH / 2), 30)
OBJECT_1_ICON_LOCATION = (int(WIDTH / 2) - 95, 30)
OBJECT_1_COUNTER_LOCATION = (int(WIDTH / 2) - 70, 30)
OBJECT_2_ICON_LOCATION = (int(WIDTH / 2) + 90, 30)
OBJECT_2_COUNTER_LOCATION = (int(WIDTH / 2) + 70, 30)
HEALT_BAR_PORTION_SIZE = (int(WIDTH / (2 * INITIAL_HEALT)), 15)
HEALT_LOCATION = (int(WIDTH / 2), HEIGHT - 20)
